### ISSUE TITLE
Create Use case diagram

### ISSUE THREAD

**Issue by msimacek** [msimacek/PA165-LibraryManager#1]
Create an Use case UML diagram with at least two user roles and put it into the project wiki (as an image).

**Comment by papperwing** [comment]
Added png and pdf file to doc/.
Also Wiki page was actualized.

**Comment by msimacek** [comment]
I think loan creation should not be done by member, but by the clerk/admin. Libraries usually aren't self-service, are they (I haven't been into one for years)? Also, can you make the wiki image bigger? It's barely readable.
